import type { Anime } from './types';

export type { Anime };

const allAnime: Anime[] = [
  {
    id: 1,
    title_russian: 'Атака Титанов',
    title_romaji: 'Shingeki no Kyojin',
    cover_image: 'https://picsum.photos/seed/101/400/600',
    genres: [{ id: 1, name: 'Action' }, { id: 2, name: 'Drama' }, { id: 3, name: 'Fantasy' }],
    watched_episodes: 24,
    total_episodes: 24,
    short_description: 'In a world where humanity resides within enormous walls, giant humanoid Titans threaten their existence.',
    full_synopsis: 'Centuries ago, mankind was slaughtered to near extinction by monstrous humanoid creatures called Titans, forcing humans to hide in fear behind enormous concentric walls. What makes these giants truly terrifying is that their taste for human flesh is not born out of hunger but what appears to be out of pleasure. To ensure their survival, the remnants of humanity began living within defensive barriers, resulting in one hundred years without a single titan encounter. However, that calm is soon shattered when a colossal Titan manages to breach the supposedly impregnable outer wall, reigniting the fight for survival against the man-eating abominations.',
    next_episode_date: null,
    release_year: 2013,
    studio: { id: 1, name: 'Wit Studio' },
    rating: 8.5,
    status: 'Completed',
    watch_status: 'Completed',
    personal_rating: 9,
    user_notes: 'A masterpiece of storytelling and animation.'
  },
  {
    id: 2,
    title_russian: 'Магическая битва',
    title_romaji: 'Jujutsu Kaisen',
    cover_image: 'https://picsum.photos/seed/102/400/600',
    genres: [{ id: 1, name: 'Action' }, { id: 4, name: 'Supernatural' }],
    watched_episodes: 12,
    total_episodes: 24,
    short_description: 'A high school student gets involved with a secret society of Jujutsu Sorcerers to eliminate a curse.',
    full_synopsis: 'Yuji Itadori is a boy with tremendous physical strength, though he lives a completely ordinary high school life. One day, to save a classmate who has been attacked by curses, he eats the finger of Ryomen Sukuna, taking the curse into his own soul. From then on, he shares one body with Ryomen Sukuna. Guided by the most powerful of sorcerers, Satoru Gojo, Itadori is admitted to the Tokyo Jujutsu High School, an organization that fights the curses... and thus begins the heroic tale of a boy who became a curse to exorcise a curse, a life from which he could never turn back.',
    next_episode_date: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString(),
    release_year: 2020,
    studio: { id: 2, name: 'MAPPA' },
    rating: 8.7,
    status: 'Ongoing',
    watch_status: 'Watching',
    personal_rating: null,
    user_notes: ''
  },
  {
    id: 3,
    title_russian: 'Твоё имя',
    title_romaji: 'Kimi no Na wa.',
    cover_image: 'https://picsum.photos/seed/103/400/600',
    genres: [{ id: 5, name: 'Romance' }, { id: 4, name: 'Supernatural' }, { id: 2, name: 'Drama' }],
    watched_episodes: 1,
    total_episodes: 1,
    short_description: 'Two teenagers share a profound, magical connection upon discovering they are swapping bodies.',
    full_synopsis: 'Mitsuha Miyamizu, a high school girl, yearns to live the life of a boy in the bustling city of Tokyo—a dream that stands in stark contrast to her present life in the countryside. Meanwhile in the city, Taki Tachibana lives a busy life as a high school student while juggling his part-time job and hopes for a future in architecture. One day, Mitsuha awakens in a room that is not her own and suddenly finds herself living the dream life in Tokyo—but in Taki\'s body! Elsewhere, Taki finds himself living Mitsuha\'s life in the humble countryside. In pursuit of an answer to this strange phenomenon, they begin to search for one another.',
    next_episode_date: null,
    release_year: 2016,
    studio: { id: 3, name: 'CoMix Wave Films' },
    rating: 9.0,
    status: 'Completed',
    watch_status: 'Planned',
    personal_rating: null,
    user_notes: 'Heard it\'s amazing, need to watch soon.'
  },
  {
    id: 4,
    title_russian: 'Семья шпиона',
    title_romaji: 'Spy x Family',
    cover_image: 'https://picsum.photos/seed/104/400/600',
    genres: [{ id: 1, name: 'Action' }, { id: 6, name: 'Comedy' }, { id: 7, name: 'Slice of Life' }],
    watched_episodes: 8,
    total_episodes: 12,
    short_description: 'A spy has to build a fake family to execute a mission, not realizing that the girl he adopts as a daughter and the woman he agrees to be in a fake marriage with are a mind reader and an assassin respectively.',
    full_synopsis: 'Corrupt politicians, nationalist extremists, and other warmongering forces constantly threaten the thin veneer of peace between neighboring countries Ostania and Westalis. In the face of these threats, the Westalian Intelligence Services (WISE) tasks its master spy, "Twilight," with a daunting mission: to spy on Donovan Desmond, the reclusive leader of an Ostanian extremist party. The mission, "Operation Strix," requires Twilight to infiltrate the prestigious Eden Academy by starting a family. He must enroll a child in the same school as Desmond\'s son and pose as a fellow parent. To do this, he quickly acquires a daughter, Anya, and a wife, Yor, unaware of their own secret identities.',
    next_episode_date: new Date().toISOString(),
    release_year: 2022,
    studio: { id: 1, name: 'Wit Studio' },
    rating: 8.6,
    status: 'Ongoing',
    watch_status: 'Watching',
    personal_rating: 10,
    user_notes: ''
  },
  {
    id: 5,
    title_russian: 'Клинок, рассекающий демонов',
    title_romaji: 'Kimetsu no Yaiba',
    cover_image: 'https://picsum.photos/seed/105/400/600',
    genres: [{ id: 1, name: 'Action' }, { id: 3, name: 'Fantasy' }, { id: 8, name: 'Historical' }],
    watched_episodes: 26,
    total_episodes: 26,
    short_description: 'A young boy becomes a demon slayer to find a cure for his sister, who has been turned into a demon.',
    full_synopsis: 'Ever since the death of his father, Tanjiro Kamado has taken it upon himself to support his family. Although their lives may be hardened by tragedy, they\'ve found happiness. But that ephemeral warmth is shattered one day when Tanjiro finds his family slaughtered and the lone survivor, his sister Nezuko, turned into a demon. To his surprise, however, Nezuko still shows signs of human emotion and thought. Thus begins Tanjiro\'s quest to fight demons and turn his sister human again.',
    next_episode_date: null,
    release_year: 2019,
    studio: { id: 4, name: 'ufotable' },
    rating: 8.8,
    status: 'Completed',
    watch_status: 'Dropped',
    personal_rating: 6,
    user_notes: 'Animation is top-tier, but the story felt a bit generic for me.'
  },
  {
    id: 6,
    title_russian: 'Провожающая в последний путь Фрирен',
    title_romaji: 'Sousou no Frieren',
    cover_image: 'https://picsum.photos/seed/106/400/600',
    genres: [{ id: 9, name: 'Adventure' }, { id: 2, name: 'Drama' }, { id: 3, name: 'Fantasy' }],
    watched_episodes: 15,
    total_episodes: 28,
    short_description: 'An elf mage reflects on her long life and the fleeting relationships she had with her former comrades.',
    full_synopsis: 'The elf mage Frieren and her courageous fellow adventurers have defeated the Demon King and brought peace to the land. But Frieren will long outlive the rest of her former party. How will she come to understand what life is, and what it means to connect with people, in a world where her own lifespan is so much greater? This is the story of an elf\'s journey to know herself and the world around her.',
    next_episode_date: new Date(new Date().setDate(new Date().getDate() + 4)).toISOString(),
    release_year: 2023,
    studio: { id: 5, name: 'Madhouse' },
    rating: 9.2,
    status: 'Ongoing',
    watch_status: 'Watching',
    personal_rating: 10,
    user_notes: 'One of the best of the decade.'
  },
   {
    id: 7,
    title_russian: 'Ковбой Бибоп',
    title_romaji: 'Cowboy Bebop',
    cover_image: 'https://picsum.photos/seed/107/400/600',
    genres: [{ id: 1, name: 'Action' }, { id: 9, name: 'Adventure' }, { id: 10, name: 'Sci-Fi' }],
    watched_episodes: 26,
    total_episodes: 26,
    short_description: 'The futuristic misadventures and tragedies of an easygoing bounty hunter and his partners.',
    full_synopsis: 'In the year 2071, humanity has colonized several of the planets and moons of the solar system leaving the now uninhabitable surface of planet Earth behind. The Inter Solar System Police attempts to keep peace in the galaxy, aided in part by outlaw bounty hunters, referred to as "Cowboys." The ragtag team aboard the spaceship Bebop are two such individuals. Mellow and carefree Spike Spiegel is balanced by his boisterous, pragmatic partner Jet Black as the pair makes a living chasing down bounties and collecting rewards. Thrown into the mix are the beautiful but bitter Faye Valentine, the eccentric computer genius Edward, and Ein, a genetically-engineered Welsh Corgi. Together, they embark on thrilling adventures that unravel each member\'s dark and mysterious past little by little.',
    next_episode_date: null,
    release_year: 1998,
    studio: { id: 6, name: 'Sunrise' },
    rating: 8.9,
    status: 'Completed',
    watch_status: 'On Hold',
    personal_rating: null,
    user_notes: 'Classic, will finish it someday.'
  },
  {
    id: 8,
    title_russian: 'Ван-Пис',
    title_romaji: 'One Piece',
    cover_image: 'https://picsum.photos/seed/108/400/600',
    genres: [{ id: 1, name: 'Action' }, { id: 9, name: 'Adventure' }, { id: 6, name: 'Comedy' }, { id: 3, name: 'Fantasy' }],
    watched_episodes: 100,
    total_episodes: 1100,
    short_description: 'Follows the adventures of Monkey D. Luffy and his pirate crew in order to find the greatest treasure ever left by the legendary Pirate, Gold Roger.',
    full_synopsis: 'Gol D. Roger was known as the "Pirate King," the strongest and most infamous being to have sailed the Grand Line. The capture and execution of Roger by the World Government brought a change throughout the world. His last words before his death revealed the existence of the greatest treasure in the world, One Piece. It was this revelation that brought about the Grand Age of Pirates, men who dreamed of finding One Piece—which promises an unlimited amount of riches and fame—and quite possibly the pinnacle of glory and the title of the Pirate King. Enter Monkey D. Luffy, a 17-year-old boy who defies your standard definition of a pirate...',
    next_episode_date: new Date(new Date().setDate(new Date().getDate() + 6)).toISOString(),
    release_year: 1999,
    studio: { id: 7, name: 'Toei Animation' },
    rating: 8.7,
    status: 'Ongoing',
    watch_status: 'Watching',
    personal_rating: 9,
    user_notes: 'The GOAT.'
  },
  {
    id: 9,
    title_russian: 'Моя геройская академия',
    title_romaji: 'Boku no Hero Academia',
    cover_image: 'https://picsum.photos/seed/111/400/600',
    genres: [{ id: 1, name: 'Action' }, { id: 6, name: 'Comedy' }],
    watched_episodes: 50,
    total_episodes: 138,
    short_description: 'A superhero-loving boy without any powers is determined to enroll in a prestigious hero academy.',
    full_synopsis: 'The appearance of "quirks," newly discovered super powers, has been steadily increasing over the years, with 80 percent of humanity possessing various abilities from manipulation of elements to shapeshifting. This leaves the remainder of the world completely powerless, and Izuku Midoriya is one such individual. Since he was a child, the ambitious middle schooler has wanted nothing more than to be a hero. Izuku\'s unfair fate leaves him admiring heroes and taking notes on them whenever he can. But it seems that his persistence has borne some fruit: Izuku meets the number one hero and his personal idol, All Might. All Might\'s quirk is a unique ability that can be inherited, and he has chosen Izuku to be his successor!',
    next_episode_date: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString(),
    release_year: 2016,
    studio: { id: 8, name: 'Bones' },
    rating: 8.4,
    status: 'Ongoing',
    watch_status: 'Watching',
    personal_rating: 8,
    user_notes: ''
  },
   {
    id: 10,
    title_russian: 'Тетрадь смерти',
    title_romaji: 'Death Note',
    cover_image: 'https://picsum.photos/seed/115/400/600',
    genres: [{ id: 4, name: 'Supernatural' }, { id: 11, name: 'Thriller' }, { id: 12, name: 'Mystery' }],
    watched_episodes: 37,
    total_episodes: 37,
    short_description: 'An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a notebook that can kill anyone whose name is written inside.',
    full_synopsis: 'A shinigami, as a god of death, can kill any person—provided they see their victim\'s face and write their victim\'s name in a notebook called a Death Note. One day, Ryuk, bored by the shinigami lifestyle and interested in seeing how a human would use a Death Note, drops one into the human realm. High school student and prodigy Light Yagami stumbles upon the Death Note and—since he deplores the state of the world—he tests the deadly notebook by writing a criminal\'s name in it. When the criminal dies immediately following his experiment with the Death Note, Light is greatly surprised and quickly recognizes how devastating the power that has fallen into his hands could be.',
    next_episode_date: null,
    release_year: 2006,
    studio: { id: 5, name: 'Madhouse' },
    rating: 8.6,
    status: 'Completed',
    watch_status: 'Completed',
    personal_rating: 10,
    user_notes: 'Classic cat and mouse thriller.'
  },
];

export const schedule = {
  "0": [8], // Sunday
  "1": [], // Monday
  "2": [2], // Tuesday
  "3": [], // Wednesday
  "4": [6], // Thursday
  "5": [9], // Friday
  "6": [4, 8], // Saturday
  allAnime: allAnime
};
