import type { Anime } from '@/types';

export const userAnimeList: Anime[] = [
  {
    id: 30276,
    title: 'One-Punch Man',
    status: 'Watching',
    score: 8.5,
    episodes_watched: 5,
    episodes_total: 12,
    image_url: 'https://placehold.co/300x450.png',
    synopsis: 'The story of Saitama, a hero who can defeat any enemy with a single punch, but is bored by the lack of challenge.',
    genres: ['Action', 'Comedy', 'Parody', 'Super Power'],
  },
  {
    id: 5114,
    title: 'Fullmetal Alchemist: Brotherhood',
    status: 'Completed',
    score: 9.1,
    episodes_watched: 64,
    episodes_total: 64,
    image_url: 'https://placehold.co/300x450.png',
    synopsis: 'Two brothers search for the Philosopher\'s Stone after an attempt to revive their deceased mother goes awry and leaves them with damaged bodies.',
    genres: ['Action', 'Adventure', 'Drama', 'Fantasy'],
  },
  {
    id: 11061,
    title: 'Hunter x Hunter (2011)',
    status: 'Watching',
    score: 9.0,
    episodes_watched: 75,
    episodes_total: 148,
    image_url: 'https://placehold.co/300x450.png',
    synopsis: 'Gon Freecss aims to become a Hunter in order to find his father. He makes friends and encounters an array of challenges along the way.',
    genres: ['Action', 'Adventure', 'Fantasy', 'Shounen'],
  },
  {
    id: 38524,
    title: 'Jujutsu Kaisen',
    status: 'Watching',
    score: 8.6,
    episodes_watched: 20,
    episodes_total: 24,
    image_url: 'https://placehold.co/300x450.png',
    synopsis: 'A boy swallows a cursed talisman - the finger of a demon - and becomes cursed himself. He enters a shaman\'s school to be able to locate the demon\'s other body parts and thus exorcise himself.',
    genres: ['Action', 'Supernatural', 'Shounen'],
  },
  {
    id: 9253,
    title: 'Steins;Gate',
    status: 'Completed',
    score: 9.0,
    episodes_watched: 24,
    episodes_total: 24,
    image_url: 'https://placehold.co/300x450.png',
    synopsis: 'A group of friends have customized their microwave into a device that can send text messages to the past.',
    genres: ['Sci-Fi', 'Thriller', 'Psychological'],
  },
  {
    id: 21,
    title: 'One Piece',
    status: 'Watching',
    score: 8.7,
    episodes_watched: 1000,
    episodes_total: 0,
    image_url: 'https://placehold.co/300x450.png',
    synopsis: 'Follows the adventures of Monkey D. Luffy and his pirate crew in order to find the greatest treasure ever left by the legendary Pirate, Gold Roger.',
    genres: ['Action', 'Adventure', 'Comedy', 'Fantasy'],
  },
  {
    id: 4181,
    title: 'Clannad: After Story',
    status: 'Completed',
    score: 8.9,
    episodes_watched: 24,
    episodes_total: 24,
    image_url: 'https://placehold.co/300x450.png',
    synopsis: 'A sequel to the slice-of-life series Clannad, After Story continues the story of Tomoya Okazaki and Nagisa Furukawa.',
    genres: ['Slice of Life', 'Romance', 'Supernatural', 'Drama'],
  },
];

export const shikimoriAnimeData: Anime[] = [
  ...userAnimeList,
  {
    id: 1535,
    title: 'Death Note',
    status: 'Completed',
    score: 8.6,
    episodes_watched: 37,
    episodes_total: 37,
    image_url: 'https://placehold.co/300x450.png',
    synopsis: 'An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a notebook that can kill anyone whose name is written in it.',
    genres: ['Mystery', 'Police', 'Psychological', 'Supernatural', 'Thriller'],
  },
  {
    id: 16498,
    title: 'Attack on Titan',
    status: 'Completed',
    score: 8.5,
    episodes_watched: 75,
    episodes_total: 75,
    image_url: 'https://placehold.co/300x450.png',
    synopsis: 'After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.',
    genres: ['Action', 'Military', 'Mystery', 'Super Power', 'Drama', 'Fantasy', 'Shounen'],
  },
  {
    id: 40028,
    title: 'Horimiya',
    status: 'Completed',
    score: 8.2,
    episodes_watched: 13,
    episodes_total: 13,
    image_url: 'https://placehold.co/300x450.png',
    synopsis: 'A secret life is the one thing they have in common. At school, Hori is a prim and perfect social butterfly, but the truth is she\'s a brash homebody. Meanwhile, under a gloomy facade, Miyamura hides a gentle heart, along with piercings and tattoos.',
    genres: ['Slice of Life', 'Comedy', 'Romance', 'School', 'Shounen'],
  },
  {
    id: 22319,
    title: 'Tokyo Ghoul',
    status: 'Completed',
    score: 7.8,
    episodes_watched: 12,
    episodes_total: 12,
    image_url: 'https://placehold.co/300x450.png',
    synopsis: 'A Tokyo college student is attacked by a ghoul, a superpowered human who feeds on human flesh. He survives, but has become part ghoul and becomes a fugitive on the run.',
    genres: ['Action', 'Mystery', 'Horror', 'Psychological', 'Supernatural', 'Drama', 'Seinen'],
  },
  {
    id: 31964,
    title: 'My Hero Academia',
    status: 'Watching',
    score: 7.9,
    episodes_watched: 113,
    episodes_total: 113,
    image_url: 'https://placehold.co/300x450.png',
    synopsis: 'A superhero-loving boy without any powers is determined to enroll in a prestigious hero academy and learn what it really means to be a hero.',
    genres: ['Action', 'Comedy', 'School', 'Shounen', 'Super Power'],
  },
  {
    id: 34599,
    title: 'Made in Abyss',
    status: 'Completed',
    score: 8.7,
    episodes_watched: 13,
    episodes_total: 13,
    image_url: 'https://placehold.co/300x450.png',
    synopsis: 'An orphaned girl named Riko lives in the Belchero Orphanage in the town of Orth. The town surrounds a strange, giant hole going deep into the earth, which is commonly called the Abyss.',
    genres: ['Sci-Fi', 'Adventure', 'Mystery', 'Drama', 'Fantasy'],
  },
  {
    id: 37521,
    title: 'Vinland Saga',
    status: 'Watching',
    score: 8.7,
    episodes_watched: 24,
    episodes_total: 24,
    image_url: 'https://placehold.co/300x450.png',
    synopsis: 'Thorfinn, the son of the greatest warrior, grew up listening to the stories of old sailors that had travelled the ocean and reached the place of legend, Vinland.',
    genres: ['Action', 'Adventure', 'Drama', 'Historical', 'Seinen'],
  }
];
